apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullstack-deployment
  namespace: microdegree  # Make sure the namespace is set to microdegree
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fullstack-app
  template:
    metadata:
      labels:
        app: fullstack-app
    spec:
      containers:
        - name: fullstack-container
          image: preema21/fullstack:20241003  # Make sure the image is correct
          ports:
            - containerPort: 8080
